import Foundation

enum AuthorCatalog {
    static let sectionTitles = [
        "Weeknight Fast",
        "One-Pan Saves",
        "Grain & Bowl",
        "Comfort Pots",
        "Bright & Fresh",
        "Bake & Toast"
    ]

    static var allDishes: [CatalogDish] {
        sectionTitles.flatMap { dishes(in: $0) }
    }

    static func dishes(in section: String) -> [CatalogDish] {
        bySection[section] ?? []
    }

    static func dish(id: String) -> CatalogDish? {
        allDishes.first { $0.id == id }
    }

    static func section(for id: String) -> String? {
        for title in sectionTitles {
            if dishes(in: title).contains(where: { $0.id == id }) {
                return title
            }
        }
        return nil
    }

    private static func dish(
        _ id: String,
        _ title: String,
        _ emoji: String,
        _ cuisine: String,
        _ minutes: Int,
        _ blurb: String,
        _ ingredients: [String],
        _ instructions: [String],
        _ tags: [String]
    ) -> CatalogDish {
        CatalogDish(
            id: id,
            title: title,
            emoji: emoji,
            cuisine: cuisine,
            minutes: minutes,
            blurb: blurb,
            ingredients: ingredients,
            instructions: instructions,
            tags: tags
        )
    }

    private static let bySection: [String: [CatalogDish]] = [
        "Weeknight Fast": [
            dish("garlic-skillet-prawns", "Garlic Skillet Prawns", "🍤", "Coastal", 18,
                 "Hot oil, quick curl, dinner before the rice finishes.",
                 ["300g prawns", "4 garlic cloves", "chili flakes", "1 lemon", "parsley", "olive oil", "salt"],
                 ["Warm oil until it shimmers, then soften sliced garlic with chili.", "Add prawns and cook until pink and just curled.", "Finish with lemon and parsley; serve immediately."],
                 ["seafood", "garlic", "lemon", "quick"]),
            dish("sesame-ginger-noodles", "Sesame Ginger Noodles", "🍜", "Pantry", 20,
                 "Cold sauce, hot noodles, one bowl on the counter.",
                 ["200g wheat noodles", "2 tbsp sesame paste", "1 tbsp ginger", "soy sauce", "1 cucumber", "sesame seeds"],
                 ["Whisk sesame paste, ginger, and soy with a splash of warm water.", "Boil noodles, drain, and rinse so they stay springy.", "Toss with sauce, cucumber ribbons, and sesame."],
                 ["noodles", "ginger", "sesame", "cucumber"]),
            dish("herb-omelette-toast", "Herb Omelette Toast", "🍳", "Home", 12,
                 "Soft eggs folded over herbs and slipped onto toast.",
                 ["3 eggs", "mixed soft herbs", "butter", "2 sourdough slices", "black pepper", "chives"],
                 ["Beat eggs with chopped herbs and pepper.", "Cook gently in butter, folding once the centre sets.", "Serve on toasted sourdough with chives."],
                 ["eggs", "herbs", "bread", "quick"]),
            dish("tomato-chickpea-skillet", "Tomato Chickpea Skillet", "🍅", "Pantry", 22,
                 "A bubbling tin of tomatoes, chickpeas, and warm spices.",
                 ["1 tin chickpeas", "1 tin chopped tomatoes", "1 onion", "2 garlic cloves", "cumin", "olive oil", "salt"],
                 ["Soften onion and garlic in oil.", "Stir in cumin, tomatoes, and drained chickpeas.", "Simmer 12 minutes and finish with salt."],
                 ["chickpeas", "tomato", "onion", "cumin"]),
            dish("miso-butter-corn", "Miso Butter Corn", "🌽", "Home", 15,
                 "Sweet corn slicked with miso butter and scallions.",
                 ["3 corn cobs", "2 tbsp butter", "1 tbsp miso", "2 scallions", "black pepper"],
                 ["Boil or steam corn until tender.", "Mash butter with miso and pepper.", "Roll hot corn through the butter and top with scallions."],
                 ["corn", "miso", "butter", "quick"]),
            dish("tuna-white-bean-salad", "Tuna White Bean Salad", "🐟", "Mediterranean", 10,
                 "No stove, just a sharp dressing and a fork.",
                 ["1 tin tuna", "1 tin white beans", "red onion", "lemon", "olive oil", "parsley", "salt"],
                 ["Drain tuna and beans into a bowl.", "Add thin red onion, oil, lemon, and parsley.", "Season and toss gently."],
                 ["tuna", "beans", "lemon", "no-cook"]),
            dish("spicy-peanut-tofu", "Spicy Peanut Tofu", "🥜", "Pantry", 25,
                 "Crisp tofu cubes under a sticky peanut drizzle.",
                 ["300g firm tofu", "3 tbsp peanut butter", "soy sauce", "chili sauce", "lime", "rice", "oil"],
                 ["Press tofu, cube, and pan-fry until golden.", "Whisk peanut butter, soy, chili, and lime with water.", "Toss tofu in sauce and serve over rice."],
                 ["tofu", "peanut", "chili", "rice"]),
            dish("lemon-garlic-orzo", "Lemon Garlic Orzo", "🍋", "Italian", 22,
                 "Tiny pasta that drinks stock and finishes bright.",
                 ["200g orzo", "2 garlic cloves", "700ml stock", "1 lemon", "parmesan", "butter", "parsley"],
                 ["Toast orzo and garlic in butter for a minute.", "Add stock gradually, stirring until creamy.", "Finish with lemon, cheese, and parsley."],
                 ["orzo", "lemon", "garlic", "stock"]),
            dish("smoky-black-bean-tacos", "Smoky Black Bean Tacos", "🌮", "Mexican", 20,
                 "Warm tortillas, smashable beans, sharp lime.",
                 ["1 tin black beans", "8 small tortillas", "1 avocado", "lime", "smoked paprika", "onion", "salt"],
                 ["Warm onion in a pan, add beans and paprika.", "Smash lightly and season.", "Fill tortillas with beans, avocado, and lime."],
                 ["beans", "avocado", "tortilla", "lime"])
        ],
        "One-Pan Saves": [
            dish("sausage-pepper-tray", "Sausage Pepper Tray", "🌶️", "Home", 35,
                 "Everything caramelises together on one sheet.",
                 ["4 sausages", "2 bell peppers", "1 red onion", "olive oil", "oregano", "salt"],
                 ["Toss peppers and onion with oil and oregano.", "Nestle sausages on the tray.", "Roast at 200°C until browned and juicy."],
                 ["sausage", "pepper", "onion", "tray"]),
            dish("honey-mustard-chicken", "Honey Mustard Chicken", "🍗", "Home", 40,
                 "Sticky thighs with roast potatoes in the same pan.",
                 ["4 chicken thighs", "400g potatoes", "2 tbsp honey", "2 tbsp mustard", "olive oil", "salt"],
                 ["Coat chicken in honey, mustard, and oil.", "Scatter potato chunks around the tray.", "Roast until chicken is cooked through."],
                 ["chicken", "potato", "honey", "mustard"]),
            dish("salmon-asparagus-bake", "Salmon Asparagus Bake", "🥦", "Coastal", 28,
                 "Fish and greens finish at the same moment.",
                 ["2 salmon fillets", "1 bunch asparagus", "lemon", "olive oil", "dill", "salt"],
                 ["Lay asparagus on a tray, drizzle with oil.", "Place salmon on top, season, add lemon slices.", "Bake until the fish flakes."],
                 ["salmon", "asparagus", "lemon", "dill"]),
            dish("mushroom-farro-bake", "Mushroom Farro Bake", "🍄", "Market", 45,
                 "Chewy grains under a blanket of roasted mushrooms.",
                 ["200g farro", "400g mushrooms", "1 onion", "stock", "thyme", "olive oil", "salt"],
                 ["Par-cook farro in stock until almost tender.", "Spread in a dish with sauteed mushrooms and onion.", "Bake until the top is bronzed."],
                 ["farro", "mushroom", "thyme", "onion"]),
            dish("harissa-cauliflower", "Harissa Cauliflower Tray", "🔥", "North African", 35,
                 "Charred florets with chickpeas and yogurt.",
                 ["1 cauliflower", "1 tin chickpeas", "2 tbsp harissa", "yogurt", "olive oil", "salt"],
                 ["Toss cauliflower and chickpeas with harissa and oil.", "Roast until edges darken.", "Serve with a cool yogurt spoonful."],
                 ["cauliflower", "chickpeas", "harissa", "yogurt"]),
            dish("maple-squash-tray", "Maple Squash Tray", "🎃", "Autumn", 40,
                 "Sweet squash, red onion, and toasted seeds.",
                 ["1 butternut squash", "1 red onion", "2 tbsp maple syrup", "pumpkin seeds", "olive oil", "salt"],
                 ["Cube squash and onion, toss with oil and maple.", "Roast until caramelised.", "Scatter seeds for crunch."],
                 ["squash", "maple", "onion", "seeds"]),
            dish("prawn-chorizo-bake", "Prawn Chorizo Bake", "🥘", "Spanish", 30,
                 "Oil from the chorizo seasons everything.",
                 ["200g prawns", "100g chorizo", "cherry tomatoes", "garlic", "olive oil", "parsley"],
                 ["Scatter chorizo and tomatoes in a dish.", "Bake until the oil runs, then add prawns and garlic.", "Finish with parsley."],
                 ["prawns", "chorizo", "tomato", "garlic"]),
            dish("pesto-gnocchi-bake", "Pesto Gnocchi Bake", "🌿", "Italian", 25,
                 "Shop gnocchi, jar pesto, bubbling mozzarella.",
                 ["500g gnocchi", "4 tbsp pesto", "mozzarella", "cherry tomatoes", "salt"],
                 ["Toss gnocchi with pesto and tomatoes.", "Top with torn mozzarella.", "Bake until the cheese stretches."],
                 ["gnocchi", "pesto", "mozzarella", "tomato"])
        ],
        "Grain & Bowl": [
            dish("harvest-grain-bowl", "Harvest Grain Bowl", "🥗", "Market", 35,
                 "Roasted roots, warm grains, sharp herb dressing.",
                 ["150g cooked farro", "1 beetroot", "1 carrot", "leafy greens", "yogurt", "dill", "lemon"],
                 ["Roast beetroot and carrot until caramelised.", "Stir dill into yogurt with lemon.", "Layer grains, greens, vegetables, and dressing."],
                 ["farro", "beetroot", "carrot", "yogurt"]),
            dish("citrus-chickpea-bowl", "Citrus Chickpea Bowl", "🍊", "Market", 25,
                 "Crisp chickpeas, orange segments, maple mustard.",
                 ["1 tin chickpeas", "1 orange", "radishes", "baby spinach", "maple syrup", "mustard"],
                 ["Roast chickpeas until they rattle.", "Segment orange and slice radishes.", "Toss spinach with maple mustard and top."],
                 ["chickpeas", "orange", "spinach", "mustard"]),
            dish("quinoa-edamame-bowl", "Quinoa Edamame Bowl", "🫛", "Pantry", 28,
                 "Protein-forward bowl with sesame crunch.",
                 ["150g quinoa", "150g edamame", "carrot", "sesame oil", "soy sauce", "scallions"],
                 ["Cook quinoa until fluffy.", "Warm edamame and grated carrot.", "Dress with sesame oil and soy; top with scallions."],
                 ["quinoa", "edamame", "carrot", "sesame"]),
            dish("brown-rice-kimchi-bowl", "Brown Rice Kimchi Bowl", "🌶️", "Korean", 30,
                 "Spicy kimchi wakes up leftover rice.",
                 ["2 cups cooked brown rice", "1 cup kimchi", "1 egg", "sesame oil", "scallions", "soy sauce"],
                 ["Warm rice in a pan with a little sesame oil.", "Push aside, fry an egg.", "Top with kimchi, soy, and scallions."],
                 ["rice", "kimchi", "egg", "sesame"]),
            dish("couscous-feta-bowl", "Couscous Feta Bowl", "🧀", "Mediterranean", 18,
                 "Steamed couscous, cucumber, olives, feta.",
                 ["150g couscous", "cucumber", "olives", "feta", "lemon", "olive oil", "mint"],
                 ["Steam couscous with boiling water and cover.", "Fluff and fold in cucumber, olives, and feta.", "Dress with lemon, oil, and mint."],
                 ["couscous", "feta", "cucumber", "olives"]),
            dish("soba-greens-bowl", "Soba Greens Bowl", "🥬", "Japanese", 20,
                 "Cold buckwheat noodles with wilted greens.",
                 ["200g soba", "bok choy", "soy sauce", "mirin", "sesame seeds", "ginger"],
                 ["Cook soba, rinse under cold water.", "Quickly wilt bok choy with ginger.", "Toss noodles with soy-mirin and greens."],
                 ["soba", "bok choy", "ginger", "soy"]),
            dish("bulgur-tomato-bowl", "Bulgur Tomato Bowl", "🍅", "Levantine", 25,
                 "Juicy tomatoes and herbs over soft bulgur.",
                 ["150g bulgur", "ripe tomatoes", "parsley", "lemon", "olive oil", "salt"],
                 ["Soak bulgur until tender.", "Chop tomatoes and parsley.", "Mix with oil, lemon, and salt."],
                 ["bulgur", "tomato", "parsley", "lemon"]),
            dish("barley-mushroom-bowl", "Barley Mushroom Bowl", "🍄", "Nordic", 40,
                 "Chewy barley with browned mushrooms.",
                 ["150g pearl barley", "300g mushrooms", "butter", "thyme", "stock", "salt"],
                 ["Simmer barley in stock until tender.", "Brown mushrooms in butter with thyme.", "Spoon mushrooms over barley."],
                 ["barley", "mushroom", "thyme", "butter"]),
            dish("wild-rice-apple-bowl", "Wild Rice Apple Bowl", "🍎", "Autumn", 45,
                 "Nutty rice, crisp apple, toasted walnuts.",
                 ["150g wild rice", "1 apple", "walnuts", "celery", "lemon", "olive oil"],
                 ["Cook wild rice until the grains split.", "Dice apple and celery; toast walnuts.", "Dress with lemon and oil."],
                 ["wild rice", "apple", "walnut", "celery"])
        ],
        "Comfort Pots": [
            dish("lentil-coconut-dal", "Lentil Coconut Dal", "🍲", "Indian", 40,
                 "Creamy red lentils with coconut and cumin.",
                 ["200g red lentils", "400ml coconut milk", "1 onion", "garlic", "cumin", "turmeric", "salt"],
                 ["Soften onion and garlic with spices.", "Add lentils, coconut milk, and water.", "Simmer until soft and season."],
                 ["lentils", "coconut", "cumin", "onion"]),
            dish("white-bean-stew", "White Bean Rosemary Stew", "🫘", "Italian", 35,
                 "A quiet pot of beans, rosemary, and bread.",
                 ["2 tins white beans", "1 onion", "carrot", "rosemary", "stock", "olive oil", "salt"],
                 ["Sweat onion and carrot in oil.", "Add beans, rosemary, and stock.", "Simmer until thick; finish with oil."],
                 ["beans", "rosemary", "carrot", "onion"]),
            dish("chicken-noodle-pot", "Chicken Noodle Pot", "🍜", "Home", 45,
                 "Clear broth, shredded chicken, soft noodles.",
                 ["2 chicken thighs", "noodles", "carrot", "celery", "onion", "stock", "parsley"],
                 ["Simmer chicken with aromatics in stock.", "Shred meat, strain broth if you like.", "Cook noodles in the broth and return chicken."],
                 ["chicken", "noodles", "carrot", "celery"]),
            dish("tomato-basil-soup", "Tomato Basil Soup", "🍅", "Home", 30,
                 "Blended tomatoes with a basil swirl.",
                 ["1 tin tomatoes", "1 onion", "garlic", "stock", "basil", "cream or olive oil", "salt"],
                 ["Sweat onion and garlic.", "Add tomatoes and stock; simmer 15 minutes.", "Blend, stir in basil and cream or oil."],
                 ["tomato", "basil", "onion", "garlic"]),
            dish("potato-leek-soup", "Potato Leek Soup", "🥔", "French", 35,
                 "Silky leeks and potatoes, no fuss.",
                 ["3 potatoes", "2 leeks", "butter", "stock", "salt", "pepper"],
                 ["Wash and slice leeks; soften in butter.", "Add cubed potatoes and stock.", "Simmer until soft, then mash or blend."],
                 ["potato", "leek", "butter", "stock"]),
            dish("chili-bean-pot", "Chili Bean Pot", "🌶️", "Tex-Mex", 40,
                 "Deep chili with beans and a cocoa hint.",
                 ["1 tin kidney beans", "1 tin tomatoes", "1 onion", "chili powder", "cumin", "cocoa powder", "salt"],
                 ["Brown onion with spices.", "Add tomatoes, beans, and a pinch of cocoa.", "Simmer until thick."],
                 ["beans", "tomato", "chili", "cumin"]),
            dish("miso-mushroom-soup", "Miso Mushroom Soup", "🍜", "Japanese", 20,
                 "Earthy broth ready in one small pot.",
                 ["4 tbsp miso", "200g mushrooms", "scallions", "tofu", "1 litre water", "soy sauce"],
                 ["Simmer mushrooms in water.", "Whisk miso with a ladle of broth, then return.", "Add tofu and scallions; do not boil hard."],
                 ["miso", "mushroom", "tofu", "scallion"]),
            dish("beef-barley-soup", "Beef Barley Soup", "🥣", "Home", 55,
                 "Slow comfort with chewy barley.",
                 ["300g stewing beef", "100g barley", "carrot", "celery", "onion", "stock", "thyme"],
                 ["Brown beef, then soften vegetables.", "Add stock, barley, and thyme.", "Simmer until beef and barley are tender."],
                 ["beef", "barley", "carrot", "thyme"]),
            dish("corn-chowder", "Corn Potato Chowder", "🌽", "Home", 35,
                 "Sweet corn, soft potato, peppery finish.",
                 ["3 corn cobs or 2 cups kernels", "2 potatoes", "1 onion", "milk or stock", "butter", "salt"],
                 ["Soften onion in butter.", "Add potato and corn with liquid.", "Simmer until potato softens; season."],
                 ["corn", "potato", "onion", "butter"])
        ],
        "Bright & Fresh": [
            dish("sun-basil-tagliatelle", "Sun Basil Tagliatelle", "🍝", "Italian", 25,
                 "Blistered tomatoes and torn basil on silky pasta.",
                 ["280g tagliatelle", "3 ripe tomatoes", "2 garlic cloves", "basil", "olive oil", "salt"],
                 ["Boil pasta; keep a cup of cooking water.", "Warm oil and garlic, then tumble in tomatoes.", "Toss pasta with sauce, basil, and pasta water."],
                 ["pasta", "tomato", "basil", "garlic"]),
            dish("charred-lemon-risotto", "Charred Lemon Risotto", "🍋", "Italian", 40,
                 "Creamy rice finished with pan-charred lemon.",
                 ["200g arborio rice", "1 lemon", "1 small onion", "700ml stock", "parmesan", "butter"],
                 ["Char lemon halves in a dry pan.", "Soften onion, stir in rice, ladle stock slowly.", "Finish with lemon juice, cheese, and butter."],
                 ["rice", "lemon", "parmesan", "onion"]),
            dish("cucumber-yogurt-salad", "Cucumber Yogurt Salad", "🥒", "Levantine", 10,
                 "Cool, crunchy, ready beside anything grilled.",
                 ["2 cucumbers", "yogurt", "garlic", "mint", "lemon", "salt"],
                 ["Dice cucumber and salt lightly.", "Stir yogurt with garlic, mint, and lemon.", "Fold cucumber through."],
                 ["cucumber", "yogurt", "mint", "garlic"]),
            dish("watermelon-feta-plate", "Watermelon Feta Plate", "🍉", "Summer", 8,
                 "Sweet, salty, and gone in minutes.",
                 ["watermelon", "feta", "mint", "olive oil", "black pepper"],
                 ["Cube watermelon and crumble feta.", "Tear mint over the top.", "Finish with oil and pepper."],
                 ["watermelon", "feta", "mint", "no-cook"]),
            dish("avocado-toast-radish", "Avocado Radish Toast", "🥑", "Home", 10,
                 "Creamy smash with peppery radish coins.",
                 ["2 avocados", "sourdough", "radishes", "lemon", "chili flakes", "salt"],
                 ["Toast the bread.", "Mash avocado with lemon and salt.", "Top with radish and chili."],
                 ["avocado", "bread", "radish", "lemon"]),
            dish("greek-chopped-salad", "Greek Chopped Salad", "🫒", "Greek", 15,
                 "Crunch in every bite, no lettuce wilt.",
                 ["cucumber", "tomato", "red onion", "olives", "feta", "olive oil", "oregano"],
                 ["Chop everything into even pieces.", "Toss with oil and oregano.", "Finish with feta."],
                 ["cucumber", "tomato", "feta", "olives"]),
            dish("mango-cabbage-slaw", "Mango Cabbage Slaw", "🥭", "Tropical", 12,
                 "Sweet mango cools the cabbage crunch.",
                 ["cabbage", "1 mango", "lime", "cilantro", "chili", "salt"],
                 ["Shred cabbage thinly.", "Cube mango and toss with lime and chili.", "Fold together with cilantro."],
                 ["cabbage", "mango", "lime", "cilantro"]),
            dish("caprese-stack", "Caprese Stack", "🍅", "Italian", 8,
                 "Tomato, mozzarella, basil — nothing else needed.",
                 ["ripe tomatoes", "mozzarella", "basil", "olive oil", "salt"],
                 ["Slice tomato and mozzarella.", "Layer with basil leaves.", "Drizzle oil and salt."],
                 ["tomato", "mozzarella", "basil", "no-cook"]),
            dish("citrus-fennel-salad", "Citrus Fennel Salad", "🍊", "Italian", 15,
                 "Shaved fennel and orange in a bright pile.",
                 ["1 fennel bulb", "2 oranges", "olive oil", "olives", "salt"],
                 ["Shave fennel paper-thin.", "Segment oranges over the bowl.", "Dress with oil, olives, and salt."],
                 ["fennel", "orange", "olives", "no-cook"])
        ],
        "Bake & Toast": [
            dish("roasted-pepper-bruschetta", "Roasted Pepper Bruschetta", "🫑", "Italian", 30,
                 "Sweet peppers and capers on toasted bread.",
                 ["1 ciabatta", "2 red peppers", "1 tbsp capers", "garlic", "olive oil", "parsley"],
                 ["Roast peppers until skins wrinkle; peel and slice.", "Toast bread and rub with garlic.", "Pile on peppers, capers, parsley, and oil."],
                 ["pepper", "bread", "garlic", "capers"]),
            dish("cheesy-garlic-flatbread", "Cheesy Garlic Flatbread", "🧄", "Home", 18,
                 "Soft flatbread blistered under cheese.",
                 ["flatbreads", "butter", "garlic", "mozzarella", "parsley"],
                 ["Mash garlic into soft butter.", "Spread on flatbreads and top with cheese.", "Bake until bubbling."],
                 ["bread", "garlic", "cheese", "butter"]),
            dish("banana-oat-bake", "Banana Oat Bake", "🍌", "Breakfast", 35,
                 "Morning bake you can slice cold later.",
                 ["3 bananas", "2 cups oats", "2 eggs", "milk", "cinnamon", "maple syrup"],
                 ["Mash bananas and mix with oats, eggs, milk, and cinnamon.", "Pour into a dish and drizzle maple.", "Bake until set and golden."],
                 ["banana", "oats", "egg", "maple"]),
            dish("savory-muffin-tray", "Savory Spinach Muffins", "🧁", "Home", 30,
                 "Portable muffins with spinach and cheese.",
                 ["2 cups flour", "2 eggs", "milk", "spinach", "cheese", "baking powder", "salt"],
                 ["Mix dry ingredients, then wet.", "Fold in chopped spinach and cheese.", "Bake in a muffin tin until risen."],
                 ["flour", "spinach", "cheese", "egg"]),
            dish("sheet-pan-pancakes", "Sheet Pan Pancakes", "🥞", "Breakfast", 25,
                 "One tray, many squares, zero flipping.",
                 ["2 cups flour", "2 eggs", "milk", "baking powder", "butter", "berries"],
                 ["Whisk batter and pour onto a lined tray.", "Scatter berries.", "Bake until set; cut into squares."],
                 ["flour", "egg", "milk", "berries"]),
            dish("herb-focaccia", "Herb Focaccia", "🌿", "Italian", 90,
                 "Dimpled dough with olive oil pools.",
                 ["500g flour", "yeast", "olive oil", "rosemary", "salt", "water"],
                 ["Mix dough and let rise until doubled.", "Press into a tray, dimple, oil, and rosemary.", "Bake until golden."],
                 ["flour", "yeast", "rosemary", "oil"]),
            dish("tomato-galette", "Tomato Galette", "🥧", "French", 55,
                 "Rustic pastry folded around ripe tomatoes.",
                 ["pie dough", "tomatoes", "cheese", "thyme", "egg", "salt"],
                 ["Roll dough and scatter cheese.", "Layer tomato slices and thyme.", "Fold edges, egg-wash, and bake."],
                 ["tomato", "pastry", "cheese", "thyme"]),
            dish("cinnamon-toast-bake", "Cinnamon Toast Bake", "🍞", "Breakfast", 40,
                 "Custardy bread cubes with cinnamon sugar.",
                 ["stale bread", "eggs", "milk", "cinnamon", "sugar", "butter"],
                 ["Cube bread into a buttered dish.", "Pour whisked eggs, milk, cinnamon, and sugar.", "Bake until puffed and set."],
                 ["bread", "egg", "milk", "cinnamon"]),
            dish("olive-cheese-scones", "Olive Cheese Scones", "🫒", "Home", 30,
                 "Savoury scones for soup night.",
                 ["2 cups flour", "butter", "cheese", "olives", "milk", "baking powder"],
                 ["Rub butter into flour and baking powder.", "Stir in cheese, olives, and milk.", "Cut rounds and bake until risen."],
                 ["flour", "cheese", "olives", "butter"])
        ]
    ]
}
